#!/bin/sh

export CI=true
export CODEBUILD=true

export CODEBUILD_PULL_REQUEST=false

if [ -z "$CODEBUILD_WEBHOOK_TRIGGER" ]; then
  export WEBHOOK=false
else
  export WEBHOOK=true
  export CODEBUILD_WEBHOOK_TYPE=$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d/ -f1)
  export CODEBUILD_WEBHOOK_TRIGGER_PART=$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d/ -f2-)
  case "$CODEBUILD_WEBHOOK_TYPE" in
    pr )
        export CODEBUILD_PULL_REQUEST=true
        export CODEBUILD_WEBHOOK_PR=${CODEBUILD_WEBHOOK_TRIGGER_PART} ;;
    branch )
        export CODEBUILD_WEBHOOK_BRANCH=${CODEBUILD_WEBHOOK_TRIGGER_PART} ;;
    tag )
        export CODEBUILD_WEBHOOK_TAG=${CODEBUILD_WEBHOOK_TRIGGER_PART} ;;
  esac

fi

export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
if [ "$CODEBUILD_GIT_BRANCH" = "" ] ; then
  CODEBUILD_GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
  export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
fi

export CODEBUILD_GIT_CLEAN_BRANCH="$(echo $CODEBUILD_GIT_BRANCH | tr '/' '.')"
export CODEBUILD_GIT_ESCAPED_BRANCH="$(echo $CODEBUILD_GIT_CLEAN_BRANCH | sed -e 's/[]\/$*.^[]/\\\\&/g')"
export CODEBUILD_GIT_MESSAGE="$(git log -1 --pretty=%B)"
export CODEBUILD_GIT_AUTHOR="$(git log -1 --pretty=%an)"
export CODEBUILD_GIT_AUTHOR_EMAIL="$(git log -1 --pretty=%ae)"
export CODEBUILD_GIT_COMMIT="$(git log -1 --pretty=%H)"
export CODEBUILD_GIT_SHORT_COMMIT="$(git log -1 --pretty=%h)"
export CODEBUILD_GIT_TAG="$(git describe --tags --exact-match 2>/dev/null)"
export CODEBUILD_GIT_MOST_RECENT_TAG="$(git describe --tags --abbrev=0)"

if [ "${CODEBUILD_GIT_BRANCH#pr-}" != "$CODEBUILD_GIT_BRANCH" ] ; then
  export CODEBUILD_PULL_REQUEST=${CODEBUILD_GIT_BRANCH#pr-};
fi

export CODEBUILD_PROJECT=${CODEBUILD_BUILD_ID%:$CODEBUILD_LOG_PATH}
export CODEBUILD_BUILD_URL="https://$AWS_DEFAULT_REGION.console.aws.amazon.com/codebuild/home?region=$AWS_DEFAULT_REGION#/builds/$CODEBUILD_BUILD_ID/view/new"

export CODEBUILD_FINAL_BRANCH=${CODEBUILD_WEBHOOK_BRANCH:-"$CODEBUILD_GIT_BRANCH"}
export CODEBUILD_FINAL_TAG=${CODEBUILD_WEBHOOK_TAG:-"$CODEBUILD_GIT_TAG"}

# Support overriding the branch and tag via an environment variable
export CODEBUILD_FINAL_BRANCH=${BRANCH_OVERRIDE:-"$CODEBUILD_FINAL_BRANCH"}
export CODEBUILD_FINAL_TAG=${TAG_OVERRIDE:-"$CODEBUILD_FINAL_TAG"}

echo "==> AWS CodeBuild Standard Environment Variables:"
env | grep ^CODEBUILD_

echo "==> AWS CodeBuild Extra Environment Variables:"
echo "==> CI = $CI"
echo "==> CODEBUILD = $CODEBUILD"
echo "==> WEBHOOK = $WEBHOOK"
echo "==> BRANCH_OVERRIDE = $BRANCH_OVERRIDE"
echo "==> TAG_OVERRIDE = $TAG_OVERRIDE"
echo "=="
echo "==> CODEBUILD_WEBHOOK_TYPE = $CODEBUILD_WEBHOOK_TYPE"
echo "==> CODEBUILD_WEBHOOK_PR = $CODEBUILD_WEBHOOK_PR"
echo "==> CODEBUILD_WEBHOOK_BRANCH = $CODEBUILD_WEBHOOK_BRANCH"
echo "==> CODEBUILD_WEBHOOK_TAG = $CODEBUILD_WEBHOOK_TAG"
echo "=="
echo "==> CODEBUILD_GIT_AUTHOR = $CODEBUILD_GIT_AUTHOR"
echo "==> CODEBUILD_GIT_AUTHOR_EMAIL = $CODEBUILD_GIT_AUTHOR_EMAIL"
echo "==> CODEBUILD_GIT_BRANCH = $CODEBUILD_GIT_BRANCH"
echo "==> CODEBUILD_GIT_CLEAN_BRANCH = $CODEBUILD_GIT_CLEAN_BRANCH"
echo "==> CODEBUILD_GIT_ESCAPED_BRANCH = $CODEBUILD_GIT_ESCAPED_BRANCH"
echo "==> CODEBUILD_GIT_COMMIT = $CODEBUILD_GIT_COMMIT"
echo "==> CODEBUILD_GIT_SHORT_COMMIT = $CODEBUILD_GIT_SHORT_COMMIT"
echo "==> CODEBUILD_GIT_MESSAGE = $CODEBUILD_GIT_MESSAGE"
echo "==> CODEBUILD_GIT_TAG = $CODEBUILD_GIT_TAG"
echo "==> CODEBUILD_GIT_MOST_RECENT_TAG = $CODEBUILD_GIT_MOST_RECENT_TAG"
echo "==> CODEBUILD_PROJECT = $CODEBUILD_PROJECT"
echo "==> CODEBUILD_PULL_REQUEST = $CODEBUILD_PULL_REQUEST"
echo "=="
echo "==> CODEBUILD_FINAL_BRANCH = $CODEBUILD_FINAL_BRANCH"
echo "==> CODEBUILD_FINAL_TAG = $CODEBUILD_FINAL_TAG"
